### ISSUE TITLE
Test-flight beta support testnet?

### ISSUE THREAD

**Issue by dabura667** [hivewallet/hive-ios#2]
Hi, sorry this is not really an issue. I was wondering if the test-flight beta would contain test-net mode or some way to do this.

All the testing and stuff I did last week was with my personal stash of BTC, 0.0001 isn't a lot, so I don't mind, but it adds up :-P

On the other hand I have plenty of testnet coins that I mined a while back.

Anyways, I can't wait to see the build. Please let me know when you're ready for external testing. Thanks.

**Comment by weilu** [comment]
hive-js does have support for testnet (not on the UI though). You just need to append ?network=testnet to the end of the URL. Not sure how that is done with the ios app. @mattlenz?

**Comment by jenbennings** [comment]
It's probably better that for the purposes of the beta if we just add it to the UI as an option (in the same way Litecoin is). There are ways of changing the web view URL, but I imagine that's going to be more work than simply adding it to the module we've already created.

**Comment by mattlenz** [comment]
Agree with Ben that it would be worth having a button in the UI, maybe next to the BTC/LTC selector. Otherwise we'd have to switch it on/off before every compile. Though we'd need a way of hiding the button in the released app?

We switch to litecoin with `window.location.assign('/?network=litecoin')` -- this causes the page to reload in Cordova. Same will apply with `/?network=testnet`.

**Comment by jenbennings** [comment]
I will add this once @haustraliaer is finished re-factoring the settings panel in hive-js [here](https://github.com/hivewallet/hive-js/issues/153).

**Comment by weilu** [comment]
@jenbennings I believe the backend is generic enough that the addition of testnet only requires an icon + one line on the view.
