### ISSUE TITLE
Can't log into litecoin 

### ISSUE THREAD

**Issue by idonthaveanametoday** [hivewallet/hive-ios#39]
I have a iphone 6plus on ios 8. I also have this issue on the web browser. BTC works fine but I get an error It gives me an internet connection error. My internet is fine on my phone and on computer which is another net work. Please look into this as I'm expecting a large ltc payout

**Comment by genecyber** [comment]
Ok I was able to verify also that on my phone the app, the web and an old hosted version are all erroring. This would lead me to believe it's a problem with blockr.io but I'll verify in a pc shortly. -Shannon

**Comment by genecyber** [comment]
I was also able to confirm that the issue is with the blockr.io API Their certificate expired today.

https://ltc.blockr.io/api/v1/address/info/LVEGL2UeVzgyiwBKNsbGAePSDMYpcabEH3,Lg8mAXogQvDs2QKudm4upKTLb2F6XAvJ79,LUzqvsPwuSKyAR4WgYS1jVjHj4TB6XXUZZ,LTAj6YpZyPe45t1VGDboPKw3JfE1ymnErn,LdzSwxT2uSX8hAAEtfFBp7TTSEYzUsJbix

![image](https://cloud.githubusercontent.com/assets/179362/5512659/1d5375d6-8794-11e4-8727-caaa47b58232.png)

A non optimal quick fix is to (in the same browser you will be using your wallet) visit the above API url and "Proceed Anyway" or "Accept Insecure Certificate"  once your browser has accepted the expired certificate litecoin calls from within hivewallet web will be able to work from your browser.

-Shannon

**Comment by idonthaveanametoday** [comment]
All I get is this message when I click continue

**Comment by genecyber** [comment]
? Which message

**Comment by idonthaveanametoday** [comment]
I still get this message

**Comment by genecyber** [comment]
Which browser?

**Comment by idonthaveanametoday** [comment]
From the app. I also put the code into safari on mobile on my phone first Iliketorun - via HopOn December 20, 2014 at 0:20 GMT, Shannon Code notifications@github.com wrote:Which browser?    On Fri, Dec 19, 2014 at 7:18 PM, idonthaveanametoday    notifications@github.com wrote:    > I still get this message   > Sent from my iPhone

**Comment by genecyber** [comment]
Ok so this workaround will not work for the app. Only if you open the wallet in the same browser you accept the expired certificate in.

**Comment by ghost** [comment]
@weilu Would you mind writing to the Blockr guys and ask if they plan to update the certificate soon?

**Comment by idonthaveanametoday** [comment]
in firefox on my browser it asked me to allow an exception. I did gave a
success message with a bunch of code i'm logging in to ltc wallet

**Comment by iamsaso** [comment]
Sorry for that guys! Certs are updated now.
